ffmpeg -y -i A.wav -f s8 -ar 0x3443 -acodec pcm_s8 A.pcm -loglevel error
ffmpeg -y -i B.wav -f s8 -ar 0x3443 -acodec pcm_s8 B.pcm -loglevel error
ffmpeg -y -i C.wav -f s8 -ar 0x3443 -acodec pcm_s8 C.pcm -loglevel error
ffmpeg -y -i D.wav -f s8 -ar 0x3443 -acodec pcm_s8 D.pcm -loglevel error
ffmpeg -y -i E.wav -f s8 -ar 0x3443 -acodec pcm_s8 E.pcm -loglevel error
ffmpeg -y -i F.wav -f s8 -ar 0x3443 -acodec pcm_s8 F.pcm -loglevel error
ffmpeg -y -i G.wav -f s8 -ar 0x3443 -acodec pcm_s8 G.pcm -loglevel error
ffmpeg -y -i H.wav -f s8 -ar 0x3443 -acodec pcm_s8 H.pcm -loglevel error
ffmpeg -y -i I.wav -f s8 -ar 0x3443 -acodec pcm_s8 I.pcm -loglevel error
ffmpeg -y -i J.wav -f s8 -ar 0x3443 -acodec pcm_s8 J.pcm -loglevel error
ffmpeg -y -i K.wav -f s8 -ar 0x3443 -acodec pcm_s8 K.pcm -loglevel error
ffmpeg -y -i L.wav -f s8 -ar 0x3443 -acodec pcm_s8 L.pcm -loglevel error
ffmpeg -y -i M.wav -f s8 -ar 0x3443 -acodec pcm_s8 M.pcm -loglevel error
ffmpeg -y -i N.wav -f s8 -ar 0x3443 -acodec pcm_s8 N.pcm -loglevel error
ffmpeg -y -i O.wav -f s8 -ar 0x3443 -acodec pcm_s8 O.pcm -loglevel error